FROM public.ecr.aws/docker/library/node:24-bookworm

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN apt update && apt install -y git vim less zsh fzf wget

RUN corepack enable && corepack prepare pnpm@11.24.0 --activate

WORKDIR /app/next-app-boilerplate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "dev"]
