FROM node:24

RUN apt update && apt install -y git vim less zsh fzf wget

RUN corepack enable && corepack prepare pnpm@10.30.2 --activate

WORKDIR /app/next-app-boilerplate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "dev"]
